name: ci-golang-workflow
on:
  push:
    branches: [ main ]  #processo de CI vai rodar toda vez que for feito um push na branch main
jobs: #jobs que serão executados
  check-application:
    name: run on Ubuntu
    runs-on: ubuntu-latest #onde a aplicação será executada
    steps:
      - uses: actions/checkout@v2 #action para fazer checkout do fonte a ser utilizado
      - uses: actions/setup-go@v2 #action de configuração de um ambiente com Golang
        with: 
          go-version: 1.15
      - run: go test ./exemplo-go # run é utilizado para executar comandos
      - run: go run ./exemplo-go/math.go