name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs: #jobs que serão executados
  check-application:
    name: run on Ubuntu #nome do job
    runs-on: ubuntu-latest #onde a aplicação será executada
    #    strategy: #permite executar a pipeline em diferentes versões da linguagem
    #      matrix:
    #        go: ["1.18", "1.19"]
    steps:
      - uses: actions/checkout@v4 #action para fazer checkout do fonte a ser utilizado
      - uses: actions/setup-go@v5 #action de configuração de um ambiente com Golang
        with:
          #go-version: ${{ matrix.go }}
          go-version: "1.19"
          cache: false
      - run: go mod init teste
      - run: go test -coverprofile=coverage.out # run é utilizado para executar comandos
      - run: go run math.go

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU #nome do passo que será executado
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push #faz build da imagem e push (quando push = true) no docker hub
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true #define se a imagem será puclicada no docker hub
          tags: tmansur/fullcycle-integracao-continua-app:latest
