name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs: #jobs que serão executados
  check-application:
    name: run on Ubuntu #nome do job
    runs-on: ubuntu-latest #onde a aplicação será executada
    strategy:
      matrix:
        go: ["1.14", "1.15"]
    steps:
      - uses: actions/checkout@v4 #action para fazer checkout do fonte a ser utilizado
      - uses: actions/setup-go@v5 #action de configuração de um ambiente com Golang
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./exemplo-go # run é utilizado para executar comandos
      - run: go run ./exemplo-go/math.go
